### ISSUE TITLE
Fix overflow issue when hovering on image

### ISSUE THREAD

**Issue by hientranea** [Code-Stellars/Travel-in-Hacktober#13]
![Screen Shot 2022-10-09 at 9 19 47 PM](https://user-images.githubusercontent.com/40749524/194762005-a10fec4c-6937-47d5-aa8f-812e2a98efc1.png)

**Comment by hientranea** [comment]
@AjCodez Could you assign me this issue?

**Comment by AjCodez** [comment]
Help would be appreciated.

**Comment by AjCodez** [comment]
👍🏼
