### ISSUE TITLE
Responsiveness issue on laptop.

### ISSUE THREAD

**Issue by AjCodez** [Code-Stellars/Travel-in-Hacktober#15]
open the site and fix the responsiveness issue in **Offers, Packages and More** section of homepage.

**Comment by AjCodez** [comment]
site link - https://code-stellars.github.io/Travel-in-Hacktober/html/index.html

**Comment by Eyesnatcher-coder** [comment]
Hello @AjCodez , please assign me the issue :)

**Comment by utkarshsingh2122** [comment]
Hey @AjCodez I can solve this

**Comment by Eyesnatcher-coder** [comment]
Hey @AjCodez , I have created a PR, Please review and Merge.

**Comment by AjCodez** [comment]
👍🏼
